# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
  ldflags:
    - -s -w -X github.com/fanux/sealos/version.Version={{.Tag}} -X  github.com/fanux/sealos/version.Build={{.ShortCommit}} -X github.com/fanux/sealos/version.BuildTime={{.Date}}
archives:
- replacements:
    linux: Linux
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

dockers:
  -
    goos: linux

    goarch: amd64

    binaries:
      - sealos

    image_templates:
      - "louisehong/{{.ProjectName}}:latest"
      - "louisehong/{{.ProjectName}}:{{.Tag}}"

    dockerfile: Dockerfile